name: 13-Simple-Workflow-On-Self-Hosted
on: workflow_dispatch
jobs: 
  my-first-job:
    runs-on: self-hosted
    steps:
      - run: pwd
  my-second-job:
    runs-on: self-hosted
    steps:
      - run: |
          pwd
          git clone https://github.com/githubtraining/hellogitworld.git
          cd hellogitworld
          pwd                                                         
          dir